### ISSUE TITLE
[Question] where do i find releases?

### ISSUE THREAD

**Issue by MohamadBayz** [simonalveteg/Workout-Tracker#42]

**Comment by MohamadBayz** [comment]
In apk i mean

**Comment by MohamadBayz** [comment]
What about a test release i would like to try it out even if it's buggy

**Comment by simonalveteg** [comment]
I'll look into what it takes to add a release to github, and hopefully I'll have some sort of beta-build for you to try out soon. Thanks for showing an interest in the app :) I'll tag you when it happens, can't give you an ETA unfortunately

**Comment by MohamadBayz** [comment]
Thanks that would be great :) love the design btw

**Comment by simonalveteg** [comment]
@MohamadBayz I have a pre-release version up now that you can try out! I'm happy to receive feedback if you have any, so don't hesitate to reach out

**Comment by MohamadBayz** [comment]
That's awesome thanks, I'll defiantly try it and will send my feedback ;)
